version: '3.2'
services:
  web:
    container_name: vehicle-monitor
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: []
    ports:
      - "8000:8000"
    volumes:
      - .:/code